name: Test coverage
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  coverage:
    name: Check test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Install stable toolchain
        run: cargo make install-stable

      - name: Install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin --version 0.20.1

      - name: Run code coverage check with tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --lib --workspace --timeout 120
